apiVersion: v1
kind: Service
metadata:
  annotations:
    cloud.google.com/app-protocols: '{"hqs-user-port":"HTTP2"}'
  name: hqs-user-service
  labels:
    app: hqs-user-service
spec:
  type: NodePort
  ports:
  - port: 443
    targetPort: 9000
    protocol: TCP
    name: hqs-user-port
  selector:
    app: hqs-user-service